// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFcSH4XMhBsS0F1FNMq6t7OHQLId65sf0',
    appId: '1:41113287228:web:5c3bb5b9c96ce49c98e139',
    messagingSenderId: '41113287228',
    projectId: 'chatapp-40a85',
    authDomain: 'chatapp-40a85.firebaseapp.com',
    storageBucket: 'chatapp-40a85.firebasestorage.app',
    measurementId: 'G-RBZGD3MZ4L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_ek1KBiiQHxw4371ONaGRyGWqr4IrIdQ',
    appId: '1:41113287228:ios:35a4ed59949205ae98e139',
    messagingSenderId: '41113287228',
    projectId: 'chatapp-40a85',
    storageBucket: 'chatapp-40a85.firebasestorage.app',
    iosBundleId: 'com.example.englishApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFcSH4XMhBsS0F1FNMq6t7OHQLId65sf0',
    appId: '1:41113287228:web:290af92c9a209d5a98e139',
    messagingSenderId: '41113287228',
    projectId: 'chatapp-40a85',
    authDomain: 'chatapp-40a85.firebaseapp.com',
    storageBucket: 'chatapp-40a85.firebasestorage.app',
    measurementId: 'G-80XVZXR1JK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_ek1KBiiQHxw4371ONaGRyGWqr4IrIdQ',
    appId: '1:41113287228:ios:35a4ed59949205ae98e139',
    messagingSenderId: '41113287228',
    projectId: 'chatapp-40a85',
    storageBucket: 'chatapp-40a85.firebasestorage.app',
    iosBundleId: 'com.example.englishApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADqihb-pTHnaKpATVl_fZ4asxDHL0Lo4c',
    appId: '1:41113287228:android:fcf875c95d66e07198e139',
    messagingSenderId: '41113287228',
    projectId: 'chatapp-40a85',
    storageBucket: 'chatapp-40a85.firebasestorage.app',
  );

}